LOCAL_PATH:= $(call my-dir)


include $(CLEAR_VARS)
LOCAL_SRC_FILES := i2c_device.c
LOCAL_MODULE := libi2c
LOCAL_MODULE_TAGS := optional
LOCAL_SHARED_LIBRARIES := liblog
LOCAL_C_INCLUDES := $(LOCAL_PATH)/include
LOCAL_CFLAGS := -Werror
#LOCAL_CFLAGS := -O2 -W -Wall
LOCAL_CFLAGS += -DLOG_LEVEL=2
LOCAL_CFLAGS += -DLOG_TO_TERM

#include $(BUILD_SHARED_LIBRARY)
include $(BUILD_STATIC_LIBRARY)


include $(CLEAR_VARS)
LOCAL_SRC_FILES := i2c_test.c
LOCAL_MODULE := i2ctest
LOCAL_MODULE_TAGS := optional
LOCAL_SHARED_LIBRARIES := liblog
LOCAL_STATIC_LIBRARIES := libi2c
LOCAL_C_INCLUDES := $(LOCAL_PATH)/include
LOCAL_CFLAGS := -Werror
LOCAL_CFLAGS += -DLOG_LEVEL=3
LOCAL_CFLAGS += -DLOG_TO_TERM
#LOCAL_CFLAGS := -O2 -W -Wall

include $(BUILD_EXECUTABLE)


